### ISSUE TITLE
Impractical DataGrid manual columns options change handling

### ISSUE THREAD

**Issue by tomshane** [DevExpress/devextreme-react#109]
### Issue Type
Question

### Description
If I understand it well, if I need to configure columns manually in the DataGrid, to handle sorting, I have to react to onOptionChanged callback, process the argument and update column properties accordingly.

Unfortunately, the argument format is very impractical for some use cases. For instance, if I click a column to change sorting the callback argument looks like this:

`{
  fullName: "columns[0].sortOrder",
  name: "columns",
  previousValue: "desc",
  value: "asc"
}`

With this information, how am I supposed to easily update column sorting properties without parsing the fullName?

### Environment Details
devextreme-react: 18.1.3-alpha.5

**Comment by IlyaKhD** [comment]
Hi,

Unfortunately, there is no more convenient way to process a single column change. This is how the DevExtreme DataGrid Widget works, the DevExtreme DataGrid React Component is a wrapper and doesn't have any enhancement for this at the moment.

For more questions regarding DevExtreme widgets' APIs, use the [DevExpress Support Center](https://www.devexpress.com/Support/Center).

If DevExtreme DataGrid React Component gets some enhancements related to this, we'll update this issue.
