### ISSUE TITLE
DateBox Navigator buttons with strange behavior

### ISSUE THREAD

**Issue by esfried** [DevExpress/devextreme-react#122]
### Issue Type
       Bug ?
![datebox](https://user-images.githubusercontent.com/5342591/41112939-bbd56220-6a56-11e8-9cb0-8c542bc493fb.png)

### Description
      DateBox wrapper problem with calendar navigator buttons and caption.

#### Steps to Reproduce
       Open the Datebox.

#### Current Behavior
       Buttons does not stay with fixed width.
      
#### Expected Behavior
      [<]     Month    [>]

### Environment Details

Chrome 65.0.3325.181 )Official Buid) (64-Bit)
Microsoft Edge 42.17134.1.0

"dependencies": {
    "devextreme": "^18.1.4-pre-18155",
    "devextreme-react": "^18.1.4-alpha.7"
    ....
}

### PS
  I fixed this in my app forcing the following css styles:

.dx-calendar-navigator .dx-button {
      width:22px;
}

.dx-calendar-navigator .dx-button.dx-state-hover  {
    width:22px;
}
  
.dx-calendar-caption-button {
    width:auto !important;
}

**Comment by lukyanovas** [comment]
Hi!
I can't reproduce the issue. See this [online example](https://stackblitz.com/edit/devextreme-react-dwoxb2?file=index.html).
Please, provide me with a sample project that reproduces the issue.

**Comment by lukyanovas** [comment]
Closed due inactivity
