### ISSUE TITLE
SlideOut and SlideOutView do not have defaultMenuVisible option

### ISSUE THREAD

**Issue by anna-zhernovkova** [DevExpress/devextreme-react#152]
### Issue Type
bug report

### Description
`menuVisible` is the dynamic option of the SlideOut and SlideOutView so it should have default* alternative to use it in uncontrolled mode.

### Demo
https://stackblitz.com/edit/devextreme-react-182usj?file=index.js

**Comment by lukyanovas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React: fix 152](https://trello.com/c/aYqjsZAx/516-react-fix-152)
