### ISSUE TITLE
Sortable headers willl show "Sort" tooltip even when not hovering

### ISSUE THREAD

**Issue by wederer** [DevExpress/devextreme-react#154]
### Issue Type
bug report

### Description
The issue is related to the component TableHaderRow (showSortingColumns enabled) and component SortingStage.

#### Steps to Reproduce
1. Sort a column
2. Minimize Browser
3. Maximize Browser
4. Wait ~500ms

#### Current Behavior
"Sort" Tooltip showing up after refocusing window even when not hovering the header.

#### Expected Behavior
Tooltip should only show on hover.

#### Demo
https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/sorting/

**Comment by lukyanovas** [comment]
Hi! I think you should ask your question in the [DevExtreme Reactive repo](https://github.com/DevExpress/devextreme-reactive/issues).

**Comment by wederer** [comment]
Ah, my bad. Will close this one.
