### ISSUE TITLE
Setting component property causes errors on IE11

### ISSUE THREAD

**Issue by AndrePinto-NET** [DevExpress/devextreme-react#176]
It seems that now setting the component attribute on "any" DevEx component (I've only tried) Button and Menu causes an error on IE: 

> Objects are not valid as a React child (found: object with keys {$$typeof, key, children, containerInfo, implementation}).

Element:
`<Button onClick={this.UserOk.bind(this)} type="success" component={this.RenderButton.bind(this, true)} />`

I've tried all variations defined on Markup Customization, and always I get the same error. The strange thing is that this code was working before, and I have no idea what changed.

**Comment by lukyanovas** [comment]
Hi!
I've tried [this example](https://stackblitz.com/edit/devextreme-react-9fwtzy?file=index.js) in IE with your markup. I don't get any exceptions in a console, could you please modify it to show an issue?

**Comment by AndrePinto-NET** [comment]
So after some reading, I've moved babel-polyfill to be the first import on my index.tsx and that did solved the problem. The only thing that I cannot understand, is that why it was working before. I did not updated any package.

In any case, you can ignore this, thank you anyway.
