### ISSUE TITLE
In DataGrid Editing component, the form mode is not working 

### ISSUE THREAD

**Issue by ankitshukla065** [DevExpress/devextreme-react#177]
### Description

The issue is related to Editing Component in Data Grid.
We can show form in editing mode for Data Grid by setting mode='form'. I tried the following way:-
<Editing mode='form' allowUpdating={true}/>

Yet, the editor was not shown as form. The editor showed the row edit method  

### Environment Details

- devextreme version:
- devextreme-react version:
- react version:

**Comment by lukyanovas** [comment]
Hi, @ankitshukla065! 
I think you forgot to attach a code snippet :)

**Comment by lukyanovas** [comment]
closed due inactivity
