### ISSUE TITLE
PieChart Series ignores Label configuration-component

### ISSUE THREAD

**Issue by IlyaKhD** [DevExpress/devextreme-react#187]
### Issue Type
bug report

### Description
The issue is related to the PieChart, its `Series` ignores nested `Label` configuration-component

#### Demo
https://stackblitz.com/edit/devextreme-react-jaulyi

### Environment Details

- devextreme-react version: 18.1.5-alpha.10 (regression, was OK in the alpha.9)

**Comment by lukyanovas** [comment]
Fixed
