### ISSUE TITLE
Re-changing the className leads to loss of devextreme classes.

### ISSUE THREAD

**Issue by Stanislav-Beresnev** [DevExpress/devextreme-react#189]
### Issue Type

"bug report"
### Description

The issue is related to className property.

#### Steps to Reproduce

1) Open demo.
2) Click button with text "Click"
3) See on "target" button
#### Demo

https://stackblitz.com/edit/devextreme-react-mqcw5y?file=index.js
### Environment Details

- devextreme version: 18.1.6-pre-18220
- devextreme-react version: 18.1.5-alpha.10 (regression, was OK in the alpha.9)
- react version: 16.4.2

**Comment by IlyaKhD** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React: fix className forwarding](https://trello.com/c/b5B80ufq/565-react-fix-classname-forwarding)
