### ISSUE TITLE
Filtering actions throw "too much recursion"

### ISSUE THREAD

**Issue by filippoitaliano** [DevExpress/devextreme-react#196]
### Issue Type
Bug report

### Description
Every time the user clicks on the table header to sort the data, or writes something in the filter box (in the filterRow), or tries to apply a filter, an error saying "too much recursion" is thrown (tested in Firefox).

#### Steps to Reproduce
The simple interaction with filters.

#### Current Behavior
Every filter interaction throws the exception.

#### Expected Behavior
The normal filtering behaviour.

#### Demo
[Stackblitz interactive demo](https://stackblitz.com/edit/react-gkkbkz?file=index.js)
[Local simple parcel-bundler demo](https://github.com/filippoitaliano/devextreme-react-grid-tests)

### Environment Details
- devextreme version: 18.1.6
- devextreme-react version: 18.1.6-alpha.11
- react version: 16.5.2

**Comment by artem-kurchenko** [comment]
Hi,

As far as I understand, we addressed this issue in the context of the [DataGrid - All the filtering actions throw "too much recursion" in React](https://www.devexpress.com/Support/Center/Question/Details/T675438/datagrid-all-the-filtering-actions-throw-too-much-recursion-in-react) thread

Feel free to reactivate that thread in case of further difficulties.
