### ISSUE TITLE
The nested Grid component cannot be added to ArgumentAxis in Chart

### ISSUE THREAD

**Issue by artem-kurchenko** [DevExpress/devextreme-react#206]
### Issue Type
Bug Report

### Description

The nested Grid  component cannot be added to ArgumentAxis

#### Steps to Reproduce
Open the example and see that the grid lines are not rendered

#### Current Behavior
The following markup doesn't work:
` <ArgumentAxis
            valueMarginsEnabled={false}          
            discreteAxisDivisionMode={'crossLabels'}
          >
            <Grid visible={true}/>
          </ArgumentAxis>`
#### Expected Behavior
This logic should work
#### Demo
https://codesandbox.io/s/70389nol1

### Environment Details

- devextreme version: 18.2.x
- devextreme-react version: 18.2.x
- react version: 16.x

**Comment by lukyanovas** [comment]
Fixed here:
https://github.com/DevExpress/devextreme-react/pull/223
https://github.com/DevExpress/devextreme-react/pull/211

You can use a simple Label component now.
