### ISSUE TITLE
The nested SeriesLabel component cannot be added to Series in Chart

### ISSUE THREAD

**Issue by roman-simionov** [DevExpress/devextreme-react#209]
### Issue Type
Bug Report

### Description
The nested SeriesLabel component is ignored.
The following markup doesn't work
```javascript
<Series type={'bar'} >
    <SeriesLabel visible={true}/>
</Series>
```

#### Steps to Reproduce
Open the example and see that the series does not have labels

#### Current Behavior
Series labels are not visible

#### Expected Behavior
Series labels are visible
#### Demo

https://codesandbox.io/s/5y88jzjn4x

### Environment Details

- devextreme version: 18.2.x
- devextreme-react version: 18.2.x
- react version: 16.x

**Comment by lukyanovas** [comment]
Fixed here:
https://github.com/DevExpress/devextreme-react/pull/223
https://github.com/DevExpress/devextreme-react/pull/211

You can use simple Label component now.
