### ISSUE TITLE
filterPanel checkbox has unexpected value and behavior

### ISSUE THREAD

**Issue by slayermass** [DevExpress/devextreme-react#216]
### Issue Type
bug report

### Description
The filterPanel checkbox at the bottom is not change filter state.

#### Steps to Reproduce
Click to 'status' filter button(☱), select any one.
Try click to filterPanel checkbox below - the checkbox is not change.

#### Current Behavior
Before clicking In html: `<input type="hidden" value="true">`.
After clicking: `<input type="hidden" value="[object Object]">`

#### Expected Behavior
The checkbox and filter are change state properly.

#### Demo
https://stackblitz.com/edit/react-c5ztsy?file=App.js

### Environment Details
The behavior is repeated on any version of devextreme-react.
- devextreme version: 18.1.6
- devextreme-react version: 18.1.6-alpha.11
- react version: 16.5.2

**Comment by IlyaKhD** [comment]
Hi,

When you set the `filterPanel` option, it is assumed to be [controlled](https://github.com/DevExpress/devextreme-react#controlled-mode). This means making it a part of the state, subscribing to the option change event, handling it, and updating the state.
 
If you want to control it - use the [onOptionChanged](https://js.devexpress.com/Documentation/18_2/ApiReference/UI_Widgets/dxDataGrid/Configuration/#onOptionChanged) option (`e.name` should be `filterPanel`).

If you don't need this - you should use an appropriate property with the `default` [prefix](https://github.com/DevExpress/devextreme-react#uncontrolled-mode). In your case, it should be `defaultFilterPanel`, but it's not available at the moment. I suggest you use a nested configuration component. 

```jsx
<DataGrid
    dataSource={columnsData}
    ...
>
    <FilterPanel visible="true" />
    ...
</DataGrid>
```

In this case `filterPanel.filterEnabled` will be uncontrolled (as not set directly).

**Comment by IlyaKhD** [comment]
We will update the issue when we add `defaultFilterPanel`.

**Comment by slayermass** [comment]
I have changed the code:
https://stackblitz.com/edit/react-c5ztsy?file=App.js
The question is why `e.value` has `object` type (equal `filterPanel` configuration)? It should be `boolean` instead.
How to control this value?

**Comment by slayermass** [comment]
Sorry, thanks. I understood how to control
