### ISSUE TITLE
Notify a user if an option is defined without the 'default' prefix and onOptionChanged is not defined

### ISSUE THREAD

**Issue by artem-kurchenko** [DevExpress/devextreme-react#219]
### Issue Type

Suggestion

### Description

We have a lot of issues related to the fact the the "default" prefix is not specified and onOptionChanged is not handled. I suggest throwing a warning message to the browser console, so users can manually identify the cause of the issue

### Environment Details

- devextreme version: 18.1
- devextreme-react version: 18.1
- react version: 16.2

**Comment by LexDX** [comment]
We will consider this enhancement in the future, but I can't provide any timeframe.
