### ISSUE TITLE
Form items will unmount after form rerendering. 

### ISSUE THREAD

**Issue by Stanislav-Beresnev** [DevExpress/devextreme-react#249]
### Issue Type

'bug report'
### Description

The issue is related to the Form

#### Steps to Reproduce

1) Open the demo and the developer console.
2) Wait 3 sec and see that the form item component will unmount after setState in Example component

#### Current Behavior
Form item component will unmount after rerendering.
#### Expected Behavior
Expected that the form item will not unmount or even will not rerender (if item props the same) after setState in Example component.
#### Demo

https://stackblitz.com/edit/devextreme-react-ft5hi8?file=index.js
### Environment Details

- devextreme version: "^18.2.2-pre-beta"
- devextreme-react version: "^18.2.3"
- react version: "^16.6.0"

**Comment by lukyanovas** [comment]
Hi!
Now this behavior is expected. DevExtreme React Component re-renders all Template Components because they can not be determined as same. We will consider to improve this behavior in future releases.
