### ISSUE TITLE
Expanding a DataGrid row MasterDetail re-renders all other expanded rows

### ISSUE THREAD

**Issue by StuMcNeill** [DevExpress/devextreme-react#261]
### Issue Type
bug report

### Description
When a DataGrid has MasterDetail enabled, expanding a row to show its MasterDetail component also re-renders every other expanded row's MasterDetail component.

This is especially noticeable if the MasterDetail component includes its own DataGrid that has a remote data source as it results in many unnecessary API calls.

This behaviour isn't seen on the jQuery or Angular demos so it looks like a React specific issue but please correct me if I'm wrong on that.

#### Steps to Reproduce
Demo code at https://codesandbox.io/s/5wk9j5o68p uses a MasterDetail component that simply displays a number which increases with each render.

1. Expand row A.
2. Expand row B.
3. Expand row C.

#### Current Behaviour

When you expand row B, row A's number changes from 1 to 2.  When you expand row C, row's A number changes to 4.  This shows every row's component is being re-rendered unnecessarily.

#### Expected Behaviour

Expanding rows should not have any affect on other already expanded rows.

#### Demo
https://codesandbox.io/s/5wk9j5o68p

### Environment Details
devextreme-react: 18.1.7-alpha.12 and 18.2.3
devextreme: 18.1.7 and 18.2.3
react: 16.2

**Comment by lukyanovas** [comment]
Hi!
Take a look at this [issue](https://github.com/DevExpress/devextreme-react/issues/90).

**Comment by StuMcNeill** [comment]
Ah yes that is very similar.  I tried both suggestions - a pure component still renders twice (https://codesandbox.io/s/vnpl6k7wr3) but manually implementing a shouldComponentUpdate method has worked (https://codesandbox.io/s/j351k7q4xy).

I'm still perplexed on why it thinks it needed a re-render but I've added a shouldComponentUpdate() to my app and that solves it for now.  Thanks for your help!
