### ISSUE TITLE
The itemKeyFn doesn't work with TabPanel widget.

### ISSUE THREAD

**Issue by Stanislav-Beresnev** [DevExpress/devextreme-react#283]
### Issue Type

bug report
### Description

The issue is related to the `TabPanel` with `itemKeyFn`.

#### Steps to Reproduce

I have the application which update own state with 5-sec interval. Application passed  into `TabPanel` copy of companies array as items. And `ItemComponent` of `TabPanel` has `console.log` in `componentWillUnmount` method for notifying about item unmounting. To prevent item unmounting i use `itemKeyFn` prop, but behavior stay the same.
#### Current Behavior
`itemKeyFn` property ignored by `TabPanel` and `ItemComponent` will be unmounted on every application state update. 
#### Expected Behavior
 `ItemComponent` must respect `itemKeyFn`.
#### Demo

https://codesandbox.io/s/qzn7k08yo6
### Environment Details

- devextreme version: ^18.2.4
- devextreme-react version: ^18.2.4
- react version: ^16.7.0

**Comment by IlyaKhD** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [React: The itemKeyFn doesn't work with TabPanel widget.](https://trello.com/c/YcRnazvq/662-react-the-itemkeyfn-doesnt-work-with-tabpanel-widget)

**Comment by Stanislav-Beresnev** [comment]
Seems like this bug https://codesandbox.io/s/4zq4y09x5w is about the same.  (Opening 3 item takes about 500ms )

**Comment by tar-z** [comment]
This issue is not related with `itemKeyFn`. Component is unmounted because TabPanel removes all its content when receives new items list. To prevent this, set TabPabel `repaintChangesOnly` option  to `true`.
