### ISSUE TITLE
Form: Tab render prop not working

### ISSUE THREAD

**Issue by ralenda** [DevExpress/devextreme-react#285]
### Issue Type
Bug Report

### Description
Form: Tab render prop not taken into account

We have a Devextreme-React form, using tabs to split it into section (Form/TabbedItem).
At some places, we have to render custom React components. Tabs and GroupItem provide render props that unfortunately do not seem to be taken into account, or sometime work in surprising ways.

The same things using template (and JQuery) props seem to work fine.

#### Steps to Reproduce
Create a Form with a Nested TabbedItem. Inside the TabbedItem
- create a Tab and use the render/tabRender/component/tabComponent props to render custom content.
- create a GroupItem inside a Tab and use the render/component props to render custom content.

#### Current Behavior
Custom content is not rendered; the render props does not seem to be ever called (that can be checked with a breakpoint).

More surprising results can be observed when specifying multiple GroupItem inside a Tab; some GroupItems seem to escape the tab (cf. the demo below)

#### Expected Behavior
The component should call the render function and render the custom component.

#### Demo
Please see https://stackblitz.com/edit/react-aukapj

### Environment Details

- devextreme version: 18.2.4
- devextreme-react version: 18.2.4
- react version: 16.5.0

**Comment by IlyaKhD** [comment]
Fixed in #289
