### ISSUE TITLE
Events muted when component is updating widget's options

### ISSUE THREAD

**Issue by IlyaKhD** [DevExpress/devextreme-react#291]
### Issue Type
bug report

### Description

The issue is related to all widgets.

Assume we have a HtmlEditor instance. If the `valueType` option changed, the `onValueChanged` callback should be fired, but it is muted - because the component is "updating props" (see the options-manager._wrapEventHandler method)

#### Current Behavior
The `onValueChanged` callback not fired

#### Expected Behavior
The `onValueChanged` callback fired

#### Demo
https://codesandbox.io/s/4z16jykwz9

Change from "Html" to "Markdown" - event not fired

### Environment Details
- devextreme-react version: 18.2.4

**Comment by LexDX** [comment]
We will research this issue in the context of the [DevExtreme Vue Widgets - Events are muted when a component updates widget's options](https://supportcenter.devexpress.com/internal/ticket/details/t860829) report.
