### ISSUE TITLE
The template contains React.lazy/Suspense

### ISSUE THREAD

**Issue by Stanislav-Beresnev** [DevExpress/devextreme-react#314]
# Feature request

**Package versions you currently use:**

    devexteme version: 18.2.6
    devextreme-react version: 18.2.6

**Description:**

We use Toolbar with the itemComponent property which contains the dynamically imported widget by React.lazy/Suspense. Also Toolbar items have the { locateInMenu: "always" } setting. Since React.Suspense firstly renders the fallback component ("...Loading"), Toolbar calculates item sizes using size of the fallback component. After import of the widget React.Suspense rerenders with the loaded widget, but Toolbar doesn't know something about it. As a result, each toolbar item has incorrect size, and doesn't get  placed in menu, as expected.

See demo with reproducing: [overview-devextreme-toolbar.zip](https://github.com/DevExpress/devextreme-react/files/2889105/overview-devextreme-toolbar.zip)

**Preferred Solution:**

Callback, or something else, which will be called (may be customer code) after loading the imported widget. It will notify Toolbar about repainting (dxResizeCallbacks.fire()) necessity. Take into account that Toolbar must  call the repaint method after all items were loaded (not after each item).
**Alternatives:**

Detect of changing the itemComponent content. Because the item widget can change his size.

**Additional Context:**

**Comment by LexDX** [comment]
We will consider this enhancement in the future, but I can't provide any timeframe.
