### ISSUE TITLE
Grouping and custom row template not working together

### ISSUE THREAD

**Issue by nhuthan** [DevExpress/devextreme-react#317]
Rows are not rendered in the correct position in them group.
Code sandbox: https://codesandbox.io/s/jz9288v825

**Comment by AlisherAmonulloev** [comment]
I did not notice any issues in the shared project. Please describe what should I do to replicate the problem? In addition, describe the result you expect.

**Comment by nhuthan** [comment]
![image](https://user-images.githubusercontent.com/12423709/53932495-698f0f00-40cc-11e9-80b8-a2b89e23f7af.png)
In the screenshot image, the rows should display in group "Title Mr.", should not after "Title Ms."

**Comment by AlisherAmonulloev** [comment]
Hi,

If you are specifying the row template, column reordering, grouping, and column fixing must be disabled. Its content cannot automatically synchronize with the column layout, which makes these features inoperative. Check https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#rowTemplate for more information.
