### ISSUE TITLE
Passing a google api key to map component doesn't work

### ISSUE THREAD

**Issue by medgar2048** [DevExpress/devextreme-react#321]
**Package versions:**

    "devextreme": "^18.2.6",
    "devextreme-react": "^18.2.6",

**Steps to reproduce:**
Pass a valid google api key to the map component.

**Current behavior:**
Currently when you pass an api key to the map component the key never makes it to the actual map key component. While debugging and breaking in the provider.dynamic.google.js file you can see that the key value is coming in empty. A warning in the console gives an idication of whats going on.
Warning: Map: `key` is not a prop
Which can be explained by the following react documentation:
https://reactjs.org/warnings/special-props.html

It seems that the map component using the key argument wont work since key is a reserved 

**Expected behavior:**
It would be nice to have a parameter such as apiKey in the react component code that would map to the key parameter in the devextreme code.

**Comment by artem-kurchenko** [comment]
@medgar2048 
 
You can use the nested "Key" component to complete this task. For instance, check the following example
 
https://codesandbox.io/s/9133oml09r

**Comment by medgar2048** [comment]
That works great. Having this solution in the documentation would be very helpful when people run into this issue. Thanks!
