### ISSUE TITLE
Unnecessary call DxLookup.FieldComponent render when lookup has empty items array

### ISSUE THREAD

**Issue by Stanislav-Beresnev** [DevExpress/devextreme-react#327]
# Bug Report

**Package versions:**

    devexteme version: 18.2.7
    devextreme-react version: 18.2.7

**Steps to reproduce:**

https://stackblitz.com/edit/devextreme-react-jqmrex?file=index.js
**Current behavior:**

My app failed on updating lookup items. ( It think it is strange, that FiledComponent rendered when this.state.items = [])

**Expected behavior:**

App works correct.

**Screenshots:**

![image](https://user-images.githubusercontent.com/12596197/54755969-44d08680-4bf8-11e9-806a-6d014529cfbb.png)

**Comment by LexDX** [comment]
We fixed this issue starting with version 18.2.8.
