### ISSUE TITLE
TreeView Item component ignores updating a visible property

### ISSUE THREAD

**Issue by Stanislav-Beresnev** [DevExpress/devextreme-react#334]
# Bug Report

**Package versions:**

    devexteme version: 18.2.7
    devextreme-react version: 18.2.7

**Steps to reproduce:**

https://codesandbox.io/s/l3n2l8vp6l

**Current behavior:**

After updating the state and setting visible to false for the second item, the item is still visible.

**Expected behavior:**

The item have to be invisible.
**Screenshots:**

**Comment by IgnatovDan** [comment]
Currently, the [option(optionName, optionValue)](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeView/Methods/#optionoptionName_optionValue) method doesn't support the "[visible](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeView/Default_Item_Template/#visible)" property.
To show or hide a tree view item change the "visible" property of a corresponding object in the TreeView datasource and call the [repaint](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeView/Methods/#repaint) method
```
            products[0].items[0].visible = false;
            treeView.repaint();
```
