### ISSUE TITLE
Slow opening and closing of popup with form

### ISSUE THREAD

**Issue by samoilis** [DevExpress/devextreme-react#359]
# Bug Report

**Package versions:**

    devexteme version: 19.1.3
    devextreme-react version: 19.1.3

**Steps to reproduce:**
[https://codesandbox.io/s/devextreme-popup-form-1q8nq](https://codesandbox.io/s/devextreme-popup-form-1q8nq)

**Current behavior:**
Slow rendering of popup with form

**Comment by geods3** [comment]
Yes this is true , I have the same problem

**Comment by LexDX** [comment]
Hi @All,

I reproduced the issue and we will research it in the context of the following report:
[Popup - The content is not rendered when the popup is opened for the first time in a certain scenario.](https://supportcenter.devexpress.com/ticket/details/t859032/popup-the-content-is-not-rendered-when-the-popup-is-opened-for-the-first-time-in-a)
