### ISSUE TITLE
Autocomplete loses focus on typing then buttons are present

### ISSUE THREAD

**Issue by egmen** [DevExpress/devextreme-react#363]
Here is an example:
https://codesandbox.io/embed/devextreme-react-grid-for-material-ui-ym7hz

First input loses focus after any character

Second one is OK

**Comment by LexDX** [comment]
Hi,

I was unable to reproduce the issue in the latest version of our components, please check the following demo:
https://codesandbox.io/s/f0fmd
I recommend you try our latest version in this scenario.

Also, I see that our components were integrated incorrectly in your sample. Please use the approach from my demo instead.
