### ISSUE TITLE
DataGrid's rowComponent breaks the dx-freespace-row logic

### ISSUE THREAD

**Issue by gdrbyKo1** [DevExpress/devextreme-react#393]
# Bug Report

**Package versions:**

    devexteme version: 19.2.4
    devextreme-react version: 19.2.4

**Steps to reproduce:**

1. Pass any React component through DataGrid's `rowComponent` JSX attribute
2. Also set the DataGrid's `height` JSX attribute to any value
3. Make sure there's not enough data provided by `dataSource` for the DataGrid rows to fill the entire widget's height
See: https://codesandbox.io/s/smoosh-breeze-21flp

**Current behavior:**

When a `rowComponent` is provided to the DataGrid component, a problem occurs with the `dx-freespace-row` row - the row is erroneously rendered visually above the actual data rows.

**Expected behavior:**

The freespace row should be located below the data rows, similar to how it works if the `rowComponent` attribute is omitted.

**Screenshots:**

![rowcomponent-freespace-row](https://user-images.githubusercontent.com/19717183/69707924-f6ff0d00-10fa-11ea-9f72-817808de7d45.png)

**Comment by gdrbyKo1** [comment]
The issue also occurs with `rowRender`, and can be easily reproduced on your demo: https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/RowTemplate/React
Just go to `data.js` and remove elements from the `employees` array, for example leaving only two elements. After you apply the changes, you'll see something like this:
![datagrid-demo-freespace-bug](https://user-images.githubusercontent.com/19717183/69955806-ca823100-14fe-11ea-813e-c100f61bd774.png)
The issue **does not** occur if you make the same change in the `jQuery`, `Angular`, `Vue`, or `AngularJS` demos. I'm not sure about the .NET demos because these demos are not interactive.

**Comment by LexDX** [comment]
Hi,

I reproduced the issue and we will research it in the context of the following report:
[DataGrid adds empty space at the top of the control when rowComponent is used to render rows and the data source has only several rows](https://supportcenter.devexpress.com/ticket/details/t858158/datagrid-adds-empty-space-at-the-top-of-the-control-when-rowcomponent-is-used-to-render)
