### ISSUE TITLE
DataGrid's rowComponent breaks the column property of onContextMenuPreparing's callback parameter

### ISSUE THREAD

**Issue by gdrbyKo1** [DevExpress/devextreme-react#394]
# Bug Report

**Package versions:**

    devexteme version: 19.2.4
    devextreme-react version: 19.2.4

**Steps to reproduce:**

1. Pass any React component through DataGrid's rowComponent JSX attribute
2. Pass a handler function through DataGrid's `onContextMenuPreparing` attribute
3. Examine the `e` object passed as the first parameter to the context menu handler function
See: https://codesandbox.io/s/late-grass-os0u1

**Current behavior:**

The `column` property of the `e` object, passed as the first parameter to the context menu handler function, is always `undefined`. The `columnIndex` property, on the other hand, works properly. The DataGrid component seems to "know" precisely which column received the `dxcontextmenu` event, but for some reason fails to provide the proper `column` object to the context menu handler function.

**Expected behavior:**

The `column` property should not be `undefined`, similar to how it works if the `rowComponent` attribute is omitted.

**Screenshots:**

n/a

**Comment by LexDX** [comment]
Hi,

The behavior you described is expected. When you specify rowComponent, you create a grid row with your own columns about which our grid does not know. So, the column and columnIndex properties are undefined:
![image](https://user-images.githubusercontent.com/42230789/73515658-2ab22800-4407-11ea-822b-00938ec060b1.png)

In this scenario, you need to manually determine the required column. For this, you can specify CSS classes for your columns. Then, you will be able to determine the target column.
