### ISSUE TITLE
DataGrid's repaintChangesOnly=true logic is broken if rowComponent is used

### ISSUE THREAD

**Issue by gdrbyKo1** [DevExpress/devextreme-react#397]
# Bug Report

**Package versions:**

    devexteme version: 19.2.4
    devextreme-react version: 19.2.4

**Steps to reproduce:**

1. Pass any React component through DataGrid's rowComponent JSX attribute
2. Set the `repaintChangesOnly` property to `true`
3. Start pushing updates to the dataSource's ArrayStore
See: https://codesandbox.io/s/mystifying-rubin-ymm6e

**Current behavior:**

When a rowComponent is provided to the DataGrid component, each update to the dataSource's ArrayStore will cause the `rowComponent` to be called `n+m` times, where `n` is the total number of rows in the dataSource, and `m` is the total number of data updates pushed to the ArrayStore so far.

**Expected behavior:**

`rowComponent` should only be rendered once per data update.
It should only be called for the row touched by the data update.

**Screenshots:**

n/a

**Comment by gdrbyKo1** [comment]
Also notice how the rendered table stays the same, even though the RowComponent is called and rendered, as evidenced by the `console.log` call at line 26 of the provided CodeSandbox demo.
The RowComponent receives new row data through props, returns an updated ReactElement which reflects the changes made to the cell data, but then the DataGrid seemingly ignores the returned row and still displays the row which was rendered during the initialisation of the widget.
If you comment out the `repaintChangesOnly={true}` prop at line 60, you will see that the row updates become visible.
This issue, along with the other issues related to the usage of the `rowComponent` prop, have been causing and are still causing us major problems while developing our app.
It looks like something is very wrong with this devextreme-react wrapper, becuse none of these issues can be reproduced in the other frameworks "supported" by DevExtreme: jQuery, Angular, Vue and AngularJS (ASP.NET not tested).
I really hope this and the remaining issues finally get some attention from the maintainers.

**Comment by LexDX** [comment]
Hi,

I reproduced the issue and we will research it in the context of the following report:
[DataGrid - The rowComponent template is not re-rendered when the repaintChangesOnly option is specified and the data source of the grid is changed](https://supportcenter.devexpress.com/ticket/details/t859033/datagrid-the-rowcomponent-template-is-not-re-rendered-when-the-repaintchangesonly-option).
