### ISSUE TITLE
CheckBox value={false} unmanaged, value={true} managed

### ISSUE THREAD

**Issue by danieleff** [DevExpress/devextreme-react#403]
# Bug Report

**Package versions:**

    devexteme version: 19.2.4
    devextreme-react version: 19.2.4

**Steps to reproduce:**

<CheckBox value={true} text={"true"} onValueChanged={() => {}} />
<CheckBox value={false} text={"false"} onValueChanged={() => {}} />

https://stackblitz.com/edit/devextreme-react-zrhqjg?file=index.js
https://devextreme-react-zrhqjg.stackblitz.io
Click on the two checkboxes

**Current behavior:**

Clicking on the "true" does not change the checkbox, which is correct.
Clickink on the "false" toggles between checked and unchecked, which is incorrect.

**Expected behavior:**

The checkboxes stay the same, the "true" always checked, the "false" always unchecked.

I tried it with previous 18.2.8 version, and it seems correct, so something broke between 18 and 19.

**Screenshots:**

**Comment by LexDX** [comment]
Hi,

I reproduced the issue and we will research it in the context of the following report:
[CheckBox - It is possible to change the value of the control when the value property is set to false](https://supportcenter.devexpress.com/ticket/details/t853788/checkbox-it-is-possible-to-change-the-value-of-the-control-when-the-value-property-is)
