### ISSUE TITLE
form updateData not re-render the compoenent which data changed

### ISSUE THREAD

**Issue by geods3** [DevExpress/devextreme-react#414]
# Bug Report

In Form component item when we call updateData and the field which we update use's render method the render doesn't called but the value correctly change's

**Package versions:**

    devexteme version: 19.2.7
    devextreme-react version: 19.2.7

**Steps to reproduce:**
https://codesandbox.io/s/zen-rgb-h3mdc?file=/src/index.js

**Current behavior:**

**Expected behavior:**

**Screenshots:**

**Comment by LexDX** [comment]
Hi @geods3,

This is expected. We do not rerender components when the updateData function is called. So, it is necessary to rerender the form completely. You can use our repaint function for this purpose:
```js
data.component.updateData("userPerms", 1);
data.component.repaint();
```
