### ISSUE TITLE
Incomplete data display

### ISSUE THREAD

**Issue by dyangel16** [DevExpress/devextreme-react#422]
# Support Question

Please do not submit support requests and "How to" questions here. Navigate to our Support Center (https://devexpress.com/sc) instead.
JS dev extreme demo page. https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/RemoteVirtualScrolling/React/Light/
issue.
Using the default code, the back-end returns 100 pieces of data, but the front-end page only displays 25 pieces of data. In the chrome toggle device toolbar, the display is normal

**Comment by LexDX** [comment]
Please submit your question to our Support Center ([https://devexpress.com/sc](https://devexpress.com/sc)) and describe the issue in greater detail. We will be happy to help you resolve this issue.
