### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by hitmanche** [DevExpress/devextreme-react#423]
#301 Bug Report

**Package versions:**

    devexteme version: 20.1.3
    devextreme-react version: 20.1.3
**Current behavior:**
When I get a data from the modal in the grid and try to apply it inline using the cellValue function with ref, I encounter such an error. Also, when I enter the update mode for the second time while updating the line, I again encounter the error in the picture. This problem does not occur when I download the version 19.1.8, but this time I get errors on the screens of the scheduler etc. Please I expect you to find a solution to this problem.

**Screenshots:**
![localhost_3000_sales(1366x768)](https://user-images.githubusercontent.com/52356400/82846865-9f97f900-9ef3-11ea-9a97-34062d8e34eb.png)

**Comment by LexDX** [comment]
Hi @hitmanche,

I am unable to determine the cause of the issue only based on your description. Please create a small sample so we can analyze and debug it on our side. Then, submit a ticket with this sample to our Support Center ([https://devexpress.com/sc](https://devexpress.com/sc)) where we will research this issue further.
