### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by Semigradsky** [DevExpress/devextreme-react#438]
Sometimes I get warnings like this:
```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of TemplateWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in TemplateWrapper (created by TemplatesRenderer)
    in TemplatesRenderer (created by DataGrid)
    ...
```
It looks like no big issue

**Comment by LexDX** [comment]
Hi @Semigradsky,

Thank you for the information. Our React widgets don't support StrictMode. We will consider replacing the use of findDOMNode in future versions. However, I can't give you any ETA. 
At the moment, I suggest you ignore the "findDOMNode is deprecated in StrictMode" warning.
