### ISSUE TITLE
Error when using devextreme-react/list - Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by paufar** [DevExpress/devextreme-react#444]
I keep getting this error when using devextreme-react/list
![image](https://user-images.githubusercontent.com/36677885/90580381-0b94af80-e20c-11ea-9f3d-1d467ff9cfb6.png)

**Comment by LexDX** [comment]
Hi @paufar,

Our React widgets don't support StrictMode. So, we can't guarantee that our controls will work in this mode. However, we will consider replacing the use of findDOMNode and add StrictMode support in future versions. However, I can't give you any ETA. 

At the moment, I recommend you disable StrictMode to resolve the issue.
