### ISSUE TITLE
Pass ref handlers into Popover's target property

### ISSUE THREAD

**Issue by mnts-i** [DevExpress/devextreme-react#446]
# Feature request

**Package versions you currently use:**

    devexteme version: 20.1.7
    devextreme-react version: 20.1.7

**Description:**
I am trying to create a Popover and attach it below a div element, setting its **target** property to the div's **ref** handler but all I get is an error. After reading the API documents I found out that this property only accepts CSS selector, jQuery Wrapper or DOM Element (I think useRef.current will return the DOM element so maybe it's a bug instead of a Feature Request??)

**Preferred Solution:**
Below is how I try to set the Popover's target property but it throws a JS error
```
import React, { useRef } from 'react'
import Popover from 'devextreme-react/popover'

const ActionsComp: React.FC = () => {
    const createControlRef = useRef<HTMLDivElement>(null!);

    return (
        <div className="app-header__controls-wrapper">
            <div className="app-header__control-item">
                <i className="fal fa-search" />
            </div>
            <div className="app-header__control-item" ref={createControlRef}>
                <i className="fal fa-plus" />
            </div>

            <Popover
                target={createControlRef.current}          // Passing the ref causes an error
                container={createControlRef.current}
                position={{ at: 'right bottom', of: createControlRef.current }}
                width={300}
                visible={true}
            >
                POPOVER TEST
            </Popover>
        </div>
    );
}

export const HeaderActions = React.memo(ActionsComp);
```

The error thrown is:
```
Uncaught TypeError: Cannot read property 'preventDefault' of undefined
    at inheritor._renderArrowPosition (popover.js:347)
    at inheritor._renderOverlayPosition (popover.js:265)
    at inheritor._renderPosition (popover.js:252)
    at inheritor._renderPosition (class.js:17)
    at inheritor._renderGeometryImpl (ui.overlay.js:970)
    at inheritor._renderGeometryImpl (popup.js:475)
    at inheritor._renderGeometryImpl (class.js:17)
    at inheritor._renderGeometry (ui.overlay.js:961)
    at inheritor._renderVisibility (ui.overlay.js:602)
    at inheritor.<anonymous> (ui.overlay.js:467)
```

As I said I assumed this would work since I thought **createControlRef.current** would return the DOM Element of the desired div but it doesn't work.

Instead, if I change the above code to use id selectors it works
```
import React, { useRef } from 'react'
import Popover from 'devextreme-react/popover'

const ActionsComp: React.FC = () => {
    const createControlRef = useRef<HTMLDivElement>(null!);

    return (
        <div className="app-header__controls-wrapper">
            <div className="app-header__control-item">
                <i className="fal fa-search" />
            </div>
            <div className="app-header__control-item" ref={createControlRef} id="create-control">
                <i className="fal fa-plus" />
            </div>

            <Popover
                target="#create-control"          // Selecting by ID
                container={createControlRef.current}
                position={{ at: 'right bottom', of: createControlRef.current }}
                width={300}
                visible={true}
            >
                POPOVER TEST
            </Popover>
        </div>
    );
}

export const HeaderActions = React.memo(ActionsComp);
```
but using CSS selectors can be cumbersome and make the app slower

**Alternatives:**

**Additional Context:**

**Comment by flagmanAndrew** [comment]
Hello,
The issue appears because the **Popover.target** option is null when the Popover is displayed. This happens because createControlRef's initial value is null - please see the following note in the [useRef doc](https://reactjs.org/docs/hooks-reference.html#useref):

Keep in mind that useRef doesn’t notify you when its content changes. Mutating the .current property doesn’t cause a re-render. If you want to run some code when React attaches or detaches a reference to/from a DOM node, you may want to use a callback ref instead.

Nevertheless, the error text doesn't give a clear idea about the cause. We are going to improve the Popover's behavior at this point in the future. Thank you for bringing this to our attention.
