### ISSUE TITLE
Default sorting and skipping focus

### ISSUE THREAD

**Issue by iliakut** [DevExpress/devextreme-react#447]
### Issue Type

Question

### Description

In the demo look at the console output. The first init of the DataGrid component sends loadOptions with a property "sort" (array that contains object with property "OrderNumber"), 
1. how can I change default value of the "sort" property (from loadOptions)? 
2. Why does changing of the sort order (by clicking on the grid header) provide property "sort" with an array with two objects with properties "OrderDate" and "OrderNumber",  instead of one? 
3. In my project at the first init loadOptions contains value "sort" === null, but in CustomStore I assigned: key = "id", and if I go to some route and than call history.back() I get "sort" === "id" because of what can it happen?  
4. If I focus some row (order number: 35703)  and than click sort by Store State it calls "load" function from "CustomStore" several times, but if I have the network call in the "load" function it will cause several network calls how can I skip "focus" if click sort?  

#### Demo

https://codesandbox.io/s/elastic-colden-lf4pq?file=/App.js

### Environment Details

- devextreme version: 19.2.4
- devextreme-react version: 19.2.4
- react version: 16.13.1

**Comment by onebalaban** [comment]
Hi,

If the issue still appears, please submit a ticket to our [[Support Center](https://supportcenter.devexpress.com/ticket/create)](https://supportcenter.devexpress.com/ticket/create). Our support team will research it and do their best to find a solution.
