### ISSUE TITLE
ERESOLVE unable to resolve dependency tree while running npx -p devextreme-cli devextreme new react-app myapp

### ISSUE THREAD

**Issue by vasiliy-mikhailov** [DevExpress/devextreme-react#495]
devextreme-cli does not create app since devextreme-react@20.2.3 requires react@"^16.2.0", but react@"^17.0.1" is installed by devextreme-cli.

**Steps to reproduce**:
npx -p devextreme-cli devextreme new react-app myapp              
✔ What layout do you want to add? › Side navigation (outer toolbar)
> npx create-react-app myapp

Creating a new React app in /Users/vmihaylov/PycharmProjects/delivery_planner/myapp.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

added 1934 packages, and audited 1934 packages in 29s

123 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Installing template dependencies using npm...

added 32 packages, and audited 1966 packages in 3s

123 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Removing template package using npm...

removed 1 package, and audited 1965 packages in 3s

123 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Success! Created myapp at /Users/vmihaylov/PycharmProjects/delivery_planner/myapp
Inside that directory, you can run several commands:

  npm start
    Starts the development server.

  npm run build
    Bundles the app into static files for production.

  npm test
    Starts the test runner.

  npm run eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd myapp
  npm start

Happy hacking!
> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myapp@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.2.0" from devextreme-react@20.2.3
npm ERR! node_modules/devextreme-react
npm ERR!   devextreme-react@"20.2.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/vmihaylov/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vmihaylov/.npm/_logs/2020-12-30T05_56_22_528Z-debug.log
1
npm ERR! code 1
npm ERR! path /Users/vmihaylov/PycharmProjects/delivery_planner
npm ERR! command failed
npm ERR! command sh -c devextreme new react-app myapp

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vmihaylov/.npm/_logs/2020-12-30T05_56_22_580Z-debug.log

**My solution**
cd myapp
rm -rf node_modules
edit package.json and replace react and react-dom version in package.json to 16.14.0 
rm package-lock.json
npm install

**Comment by LexDX** [comment]
Hi @vasiliy-mikhailov,

We fixed this issue in v.21.1.3. Please refer to this report for more information:
[Popover - onClick event handlers in template elements do not work with React v17.0.0](https://supportcenter.devexpress.com/ticket/details/t941721/popover-onclick-event-handlers-in-template-elements-do-not-work-with-react-v17-0-0#)
