### ISSUE TITLE
mobx+React/TS; E1010 - The template does not contain the TextBox widget

### ISSUE THREAD

**Issue by allenm84** [DevExpress/devextreme-react#506]
# Bug Report

**Package versions:**

    devexteme version: 20.2.5
    devextreme-react version: 20.2.5

**Steps to reproduce:**

https://codesandbox.io/s/devextreme-e1010-error-4zjx2?file=/src/AppView.js

Sometimes the error appears immediately. Otherwise, change the selection of the first SelectBox

**Current behavior:**

E1010 appears when changing SelectBox

**Expected behavior:**

E1010 does not appear

**Screenshots:**

![image](https://user-images.githubusercontent.com/32555233/109337088-e8d1fc00-7829-11eb-9330-38e9599b9bf6.png)

**Comment by onebalaban** [comment]
Hi,

Use `defaultValue` instead of `value`: [CodeSandBox](https://codesandbox.io/s/devextreme-e1010-error-forked-895jo?file=/src/AppView.js).
