### ISSUE TITLE
Failed to execute 'removeChild' on 'Node' in Doughnut chart

### ISSUE THREAD

**Issue by ColinMcD01** [DevExpress/devextreme-react#548]
### Issue Type

bug report

### Description

If you are using a doughnut chart with a custom label in the center, and the datasource gets updated you receive an error:
"Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node." in TemplateWrapper

#### Steps to Reproduce

Using a Doughnut chart with a custom label in the center
Update chart's datasource through react state/props

#### Current Behavior
Everything breaks with the above error

#### Expected Behavior
Chart should update to reflect new data with no errors

#### Demo

I have taken your demo for a doughnut chart with label in the center and added functionality to update the datasource when you click a button. It demonstrates the issue.
https://codesandbox.io/s/custom-label-in-the-center-devextreme-charts-forked-xv3ry

### Environment Details

- devextreme version: 20.2.7
- devextreme-react version: 20.2.7
- react version: 16.14.0

(I have seen similar issues with updating the TagBox UI component, same error, coming from TemplateWrapper. That was harder to reproduce however.)

**Comment by LexDX** [comment]
Hi @ColinMcD01,

We fixed this issue in the context of this report:
[Chart / Gantt / Diagram - The "NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node." error occurs when contentRender is used in Tooltip](https://supportcenter.devexpress.com/ticket/details/t998346/chart-gantt-diagram-the-notfounderror-failed-to-execute-removechild-on-node-the-node-to)
