### ISSUE TITLE
`setLoadPanelOptions` ruined export performance

### ISSUE THREAD

**Issue by Semigradsky** [DevExpress/devextreme-react#559]
# Bug Report

**Package versions:**

    devexteme version:
    devextreme-react version:

**Steps to reproduce:**
My code
```ts
import { ExcelDataGridCell, exportDataGrid } from 'devextreme/excel_exporter'
import { Cell, Workbook } from 'exceljs'
import { saveAs } from 'file-saver'

const workbook = new Workbook()
const worksheet = workbook.addWorksheet('Sheet')
await exportDataGrid({
  component: dataGrid,
  worksheet,
})

const buffer = await workbook.xlsx.writeBuffer()
saveAs(new Blob([buffer], { type: 'application/octet-stream' }), `${filename}.xlsx`)
```
`dataGrid` is `dxDataGrid` with hundreds rows and custom `cellTemplate`s.

**Current behavior:**
`exportDataGrid` doesn't take long. But inside it calls `component._setOptionWithoutOptionChange("loadPanel", options);` which causes datagrid rerender (much more slow than initial datagrid render time).

**Screenshots:**
Performance for 50 rows in datagrid:
![image](https://user-images.githubusercontent.com/1198848/118819267-da8dfc00-b8bd-11eb-87da-ff3843ac0e29.png)
![image](https://user-images.githubusercontent.com/1198848/118819363-f5607080-b8bd-11eb-97be-dd3d654234b2.png)

---

My workaround:
```ts
  const Export = require('devextreme/exporter/exceljs/export').Export
  Export.setLoadPanelOptions = () => {}
```

**Comment by novsstation** [comment]
Hi Dmitry,

Unfortunately, I could not reproduce this issue.
As you can see in the picture below, rendering of the load panel takes only a small part of the export time, while the biggest part is processing of exported data. Updating load panel options doesn't cause re-rendering of the grid.

![image](https://user-images.githubusercontent.com/57402891/119817599-d9308500-bef6-11eb-8fb5-abb01f7c5973.png)

Perhaps, there are some specific options that affect performance.
Could you please create a sample project or modify [my sample](https://codesandbox.io/s/overview-devextreme-data-grid-forked-bwlc3?file=/App.js) to illustrate the issue?

**Comment by Semigradsky** [comment]
@novsstation Hi! I reproduced here: https://codesandbox.io/s/github/Semigradsky/devextreme-export-performance-regress/tree/main/

Performance degradation happens if I add `loadPanel` property to `DataGrid` or to `defaultProps`:
```
    DataGrid.defaultProps = {
      loadPanel: {
        enabled: false
      }
    };
```
In this case `OptionsManager.setValue` is called and something happens for a long time.

**Comment by novsstation** [comment]
Hi,

Thank you for your sample. I reproduced the problem and created a public bug report regarding this issue in our support center.
You can track the progress [here](https://supportcenter.devexpress.com/internal/ticket/details/t1003647).

As a workaround, you can turn off loadPanel similar to your default props.
Set the [loadPanel.enabled](https://js.devexpress.com/Documentation/ApiReference/Common/Object_Structures/ExcelExportDataGridProps/loadPanel/#enabled) = false in the arguments of the exportDataGrid function:

```js
    exportDataGrid({
      component: e.component,
      worksheet: worksheet,
      loadPanel: { enabled: false }
    });
```
