### ISSUE TITLE
Diagram - Custom Shapes - Templates with Editing example is not working

### ISSUE THREAD

**Issue by anandrikka** [DevExpress/devextreme-react#562]
The following react example from documentation is not working
https://js.devexpress.com/Demos/WidgetsGallery/Demo/Diagram/CustomShapesWithTemplatesWithEditing/React/Light/

# Bug Report

**Package versions:**

    devexteme version: 20.2.7
    devextreme-react version: 20.2.7

**Steps to reproduce:**
https://codesandbox.io/s/templates-with-editing-devextreme-diagram-forked-vlh5h?file=/index.js

**Current behavior:**
dragging new custom element into workspace is throwing error

**Expected behavior:**
user should be able to add custom elements without any error.

**Screenshots:**

**Comment by LexDX** [comment]
Hi @anandrikka,

The issue was fixed in the context of this report: https://supportcenter.devexpress.com/ticket/details/t998346/chart-gantt-diagram-the-notfounderror-failed-to-execute-removechild-on-node-the-node-to
