### ISSUE TITLE
TreeView with search mode

### ISSUE THREAD

**Issue by angabar** [DevExpress/devextreme-react#627]
# Bug Report

TreeView with multiselect checkboxes dosen't work with searchbar

**Package versions:**

    devexteme version: 21.2.3
    devextreme-react version: 21.2.3

**Steps to reproduce:**

Add `searchEnabled` and `searchMode` props on TreeView with multi node selection.

[Example](https://codesandbox.io/s/node-selection-and-customization-devextreme-tree-view-forked-xlug5?file=/App.js:1521-1529)

**Current behavior:**
Search text dosen't work, always show "No data to display"

**Expected behavior:**
Nodes filtered like [this](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeView/TreeViewWithSearchBar/React/Light/)

**Screenshots:**
![1](https://user-images.githubusercontent.com/4190084/140395979-e11ac3fe-f9bc-4856-9469-201accf65e48.png)
![2](https://user-images.githubusercontent.com/4190084/140395993-66b16ad6-3c7b-48d5-87ca-9e08c87750b5.png)

**Comment by onebalaban** [comment]
Hi,

I've got the "Sandbox not found" error. Could you please share a CSB project?

**Comment by onebalaban** [comment]
Configure the [searchExpr](https://js.devexpress.com/Documentation/ApiReference/UI_Components/dxTreeView/Configuration/#searchExpr) property to specify custom search fields: [CodeSandBox](https://codesandbox.io/s/627-9yimu).
