### ISSUE TITLE
Test DataGrid doesn't render component

### ISSUE THREAD

**Issue by thiagocardoso1988** [DevExpress/devextreme-react#635]
### Issue Type

Bug Report

### Description

The issue is related to testing a component.

When using a blank DataGrid, i.e., doesn't passing any datasource but specifying the `no-data-text` property it renders accordingly, but passing a datasource (even an empty one) it doesn't render.

#### Steps to Reproduce

- Uses Jest as a test runner
- Creates a test file
- Tries to render DataGrid with some content
- Run test file

#### Current Behavior
It doesn't render passed datasource (it renders blank, with no data at all)

#### Expected Behavior
To render datagrid correctly with the passed datasource

### Environment Details

- devextreme version: "^21.1.4"
- devextreme-react version: "^21.1.4"
- react version: "^17.0.2"

**Comment by onebalaban** [comment]
Hi,

Could you please submit a ticket to our [support center](https://devexpress.com/ask) and attach a demo project to demonstrate the issue?
