### ISSUE TITLE
Setting columns option in dxDataGrid with dataSource with OdataStore break the sorting.

### ISSUE THREAD

**Issue by Stanislav-Beresnev** [DevExpress/devextreme-react#70]
### Issue Type

bug report
### Description
When i set the columns option and try to change sort in any column, data order doesn't change. If columns options isn't be used all works as expected.
#### Current Behavior
After click on columnt to sort, widget data will be reolad, but the order will not change.
#### Expected Behavior
Expected that sorting in widget with columns option will be the same as in the widget without columns option.
### Steps to Reproduce

1. Set the dataSource with odata store to widget.
2. Set the columns option to widget.
2. Try to sort column.
#### Demo

Demo with React widget to reproduce (reuire to enable corse): https://stackblitz.com/edit/devextreme-react-5bymhn?file=index.js

Just want to say that original dxDataGrid (non react widget) work good, for example see this demo: https://codepen.io/anon/pen/mLJpRR

### Environment Details

devextreme 18.1.1-pre-18093
devextreme-react 18.1.1-alpha.3
react 16.3.0

**Comment by lukyanovas** [comment]
Hi! 
Now it works as expected. DataGrid sorting configures inside the `columns` option. You should process changes of the `columns` option via `optionChanged` callback or use `defaultColumns` option if you don't want to control the `columns`.

**Comment by Stanislav-Beresnev** [comment]
Hi!
Ok, using `defaultColumns` option is good solution for us.
Thank you for all your assistance.
