### ISSUE TITLE
dxDataGrid: it is impossible to use pager options.

### ISSUE THREAD

**Issue by Stanislav-Beresnev** [DevExpress/devextreme-react#76]
### Issue Type

bug report
### Description
There is should be possible to set uncontrolled pager options.
#### Current Behavior
When i set these pager options:
`pager={{
          showPageSizeSelector: true,
          allowedPageSizes: [5, 10, 20],
          showInfo: true
}}`
and try to change pageSize value in data grid, all re rendered with default pageSize value, instead selected.
#### Expected Behavior
Expected that after changing pageSize value, dataGrid will be re rendered with new pageSize value instead default.
### Steps to Reproduce

1. Set the pager options from example.
2. try to change pageSize value in data grid/
#### Demo

https://stackblitz.com/edit/devextreme-react-sirzqz?file=index.js
### Environment Details

devextreme 18.1.1-pre-18093
devextreme-react 18.1.1-alpha.3
react 16.3.0

**Comment by IlyaKhD** [comment]
Hi,
Currently, the uncontrolled mode is broken for this option, so you have to handle the `optionChanged` event.

Gonna fix it in the next alpha.

**Comment by IlyaKhD** [comment]
The thing that prevented the DataGrid from re-rendering correctly was the `paging` option (not the `pager` one).

We've added the `defaultPaging' option to resolve the issue (coming in the alpha-5).
