### ISSUE TITLE
List widget with elementAttr option has strange behaviour.

### ISSUE THREAD

**Issue by Stanislav-Beresnev** [DevExpress/devextreme-react#78]
### Issue Type

bug report
### Description
I have list widget that palced in contanier component. List widget items listen onClick event and show alert message on firing this event. Also list widget listen onItemClick event and change parent state on firing this event. (This is the simulating navigate to view function that change location in browser. Our layout has master pane with list and detail pane with item content, so list should be unchanged.)
#### Current Behavior
If i set elementAttr option to list and click list items, after click list will be lose selection and click on list item will not be have some effect.
#### Expected Behavior
Expected that elementAttr will not affect to the widget behavior.
### Steps to Reproduce

See demo with reproducing
#### Demo

https://stackblitz.com/edit/devextreme-react-ozanfd?file=index.js
### Environment Details

devextreme 18.1.1-pre-18093
devextreme-react 18.1.1-alpha.3
react 16.3.0

**Comment by IlyaKhD** [comment]
Hi,
The elementAttr option is updated on each call to the `MyList.render` method (since a new object is created each time).

Sharing a single object between render calls (e.g. making it a field) should help to overcome the problem.

```js
  render() {
    return (
      <List
        /* * * */
        elementAttr={this.attrs}
        /* * * */
      />
    );
  }
```
