### ISSUE TITLE
Gantt. taskContentRender. Generating empty TemplateWrapper components 

### ISSUE THREAD

**Issue by WhoAmIRUS** [DevExpress/devextreme-react#782]
# Bug Report

**Package versions:**

    devexteme version: 22.1.4
    devextreme-react version: 22.1.4

**Steps to reproduce:**
https://codesandbox.io/s/task-template-devextreme-gantt-forked-yx0f5m

**Current behavior:**
I try to provide to taskContentRender props with value taskContentRender. And I wrap taskContentRender value in useCallback hook, because i have dependency of some other prop (number in example). But when this props is changes, in VDOM I see empty TemplateWrapper and new TemplateWrapper. And count of TemplateWrappers increase every time i update this props.

**Expected behavior:**
I expect, that TemplateWrapper will not duplicate, and only old one will change

**Screenshots:**
<img width="476" alt="Снимок экрана 2022-10-21 в 18 44 20" src="https://user-images.githubusercontent.com/29947304/197223958-c2458505-ceff-4aaf-915b-8dcfdaa55ee8.png">

<img width="228" alt="image" src="https://user-images.githubusercontent.com/29947304/197224212-e2395f98-edff-4579-9a87-09e0cd9d1885.png">

**Comment by artem-kurchenko** [comment]
Hi,

Thank you for the report. The number of templates should always reflect the number of elements on the pae. We'll research this issue in the following thread: https://supportcenter.devexpress.com/ticket/details/t1126223/react-gantt-doesn-t-clear-templatewrapper-instances-when-the-corresponding-template-is
