### ISSUE TITLE
Gantt. Bug when collapse tasks open after update tasks data

### ISSUE THREAD

**Issue by WhoAmIRUS** [DevExpress/devextreme-react#783]
**Package versions:**

    devexteme version: 22.1.4
    devextreme-react version: 22.1.4

**Steps to reproduce:**

1. Collapse tasks
2. Press button update

https://codesandbox.io/s/task-template-devextreme-gantt-forked-xnyjrf?file=/App.js

**Current behavior:**
Tasks in tree list are open, but gantt graphic not view opened tasks.

**Expected behavior:**
Do not expand collapsed tasks

**Screenshots:**
Initial:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/29947304/198536554-d905be01-4100-4bc6-987b-9f6264e02530.png">

Result:
<img width="962" alt="image" src="https://user-images.githubusercontent.com/29947304/198536463-c247459c-ff08-4ea4-a127-2b178c14d7fb.png">

**Comment by artem-kurchenko** [comment]
Hello,

Thank you for the detailed report. I forwarded this issue to our Support Center: https://supportcenter.devexpress.com/ticket/details/t1125635/gantt-doesn-t-update-the-tasks-view-if-datasource-was-updated

Please refer to it for further correspondence.
