### ISSUE TITLE
Style and className props missing on widgets

### ISSUE THREAD

**Issue by tomshane** [DevExpress/devextreme-react#89]
### Issue Type
Feature request

### Description
Widgets like Button, TextBox and others are not accepting style and className props. If I want to place two Buttons next to each other with a margin between them, I have to wrap them in a div.

### Environment Details
devextreme 18.1.1-pre-18093
devextreme-react 18.1.1-alpha.4
react 16.3.0
typescript 2.8

**Comment by IlyaKhD** [comment]
Hi,
Currently, className and style props are not supported but you can use the `elementAttr` prop instead:
```jsx
<Button text="Button with style attr" elementAttr={{ style: "background-color: #ffc" }} />
```
