### ISSUE TITLE
List re-renders itemComponent multiple times

### ISSUE THREAD

**Issue by Dem0n13** [DevExpress/devextreme-react#90]
### Issue Type
bug report

### Description
List re-renders itemComponent multiple times on "More" button or filter changing

#### Steps to Reproduce
1. Init list with dataSource (pageSize < item.length) and itemComponent (log props)
2. Click "More"
3. See console

#### Current Behavior
For 20 items it calls itemComponent 600+ times

#### Expected Behavior
For 20 items it calls itemComponent ~20 times

#### Demo
https://stackblitz.com/edit/devextreme-react-xruggw?file=index.js

### Environment Details
devextreme 18.1.1-pre-18093
devextreme-react 18.1.1-alpha.4
react 16.3.0

**Comment by lukyanovas** [comment]
To avoid the unnecessary re-renders implement the [shouldComponentUpdate] (https://reactjs.org/docs/react-component.html#shouldcomponentupdate) method for your ItemComponent or use the [PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent) like in [this example](https://stackblitz.com/edit/devextreme-react-7c2hzs?file=index.js).

See also:
https://reactjs.org/docs/optimizing-performance.html#shouldcomponentupdate-in-action
https://reactjs.org/docs/optimizing-performance.html#examples
